export const ActionTypes = {
    // Redux Action Types
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    DECREMENT_QTY: 'DECREMENT_QTY',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    LAST_REMOVED: 'LAST_REMOVED',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_OUT: 'LOGGED_OUT',
}